In [1]:
import pandas as pd

In [2]:
df_ativos_limpo = pd.read_csv(r'..\data\processed\ativos_limpo.csv', sep=';') 
df_vulnerabilidades_limpo = pd.read_csv(r'..\data\processed\vulnerabilidades_limpo.csv', sep=';')

display(df_ativos_limpo)
display(df_vulnerabilidades_limpo)

,ativo_id,sistema,criticidade,dominio,ambiente,localidade,status_ativo
0,A0001,Sistema_1,Crítica,Dominio_2,Homologação,São Paulo,Em desativação
1,A0002,Sistema_2,Média,Dominio_3,Produção,São Paulo,Em desativação
2,A0003,Sistema_3,Média,Dominio_4,Homologação,São Paulo,Ativo
3,A0004,Sistema_4,Alta,Dominio_5,Homologação,Campinas,Ativo
4,A0005,Sistema_5,Alta,Dominio_6,Produção,Recife,Ativo
...,...,...,...,...,...,...,...
195,A0196,Sistema_196,Baixa,Dominio_5,Desenvolvimento,Recife,Ativo
196,A0197,Sistema_197,Alta,Dominio_6,Homologação,Curitiba,Ativo
197,A0198,Sistema_198,Baixa,Dominio_7,Desenvolvimento,São Paulo,Em desativação
198,A0199,Sistema_199,Crítica,Dominio_8,Homologação,Recife,Ativo
199,A0200,Sistema_200,Alta,Dominio_9,Homologação,Curitiba,Ativo

,vuln_id,ativo_id,severidade_corrigida,cvss_score,origem,status_vulnerabilidade,data_abertura,data_correcao,sistema,criticidade_ativo,ambiente,status_ativo,flag_ativo_orfao,flag_data_abertura_invalida,flag_data_correcao_futura,flag_erro_data_sla,dias_para_correcao
0,V00001,A0078,Baixa,2.8,Cloud Security,Em tratamento,2026-03-21,NaN,Sistema_78,Crítica,Homologação,Ativo,False,False,NaN,0,NaN
1,V00002,A0060,Alta,7.5,Qualys,Em tratamento,2026-06-01,NaN,Sistema_60,Média,Não Mapeado,Ativo,False,False,NaN,0,NaN
2,V00003,A0080,Baixa,1.7,Veracode,Aberta,2026-08-18,NaN,Sistema_80,Crítica,Produção,Ativo,False,False,NaN,0,NaN
3,V00004,A0086,Baixa,2.5,Qualys,Aberta,2026-06-16,NaN,Sistema_86,Média,Produção,Ativo,False,False,NaN,0,NaN
4,V00005,A0089,Média,4.4,Cloud Security,Em tratamento,2026-02-12,NaN,Sistema_89,Média,Produção,Ativo,False,False,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,V00101,A9999,Baixa,3.9,Cloud Security,Aceita,2026-06-08,NaN,Sistema Desconhecido,Não Mapeado,Ambiente Desconhecido,Desconhecido,True,False,NaN,0,NaN
1996,V00501,A9999,Média,4.7,Veracode,Em tratamento,2026-05-07,NaN,Sistema Desconhecido,Não Mapeado,Ambiente Desconhecido,Desconhecido,True,False,NaN,0,NaN
1997,V00901,A9999,Média,5.8,Cloud Security,Corrigida,2026-01-04,2026-03-29,Sistema Desconhecido,Não Mapeado,Ambiente Desconhecido,Desconhecido,True,False,False,0,84.0
1998,V01301,A9999,Alta,7.5,Cloud Security,Corrigida,2026-07-21,2026-09-23,Sistema Desconhecido,Não Mapeado,Ambiente Desconhecido,Desconhecido,True,False,False,0,64.0
1999,V01701,A9999,Média,5.8,Cloud Security,Corrigida,2026-04-08,2026-05-31,Sistema Desconhecido,Não Mapeado,Ambiente Desconhecido,Desconhecido,True,False,False,0,53.0