In [14]:
import pandas as pd
import numpy as np

In [15]:
df_ativos = pd.read_csv(r'..\data\raw\ativos.csv', sep=';')
df_vulnerabilidades = pd.read_csv(r'..\data\raw\vulnerabilidades.csv', sep=';')

In [16]:
print(df_ativos.info())
df_ativos.head(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ativo_id      200 non-null    object
 1   sistema       200 non-null    object
 2   criticidade   199 non-null    object
 3   dominio       200 non-null    object
 4   ambiente      198 non-null    object
 5   localidade    200 non-null    object
 6   status_ativo  200 non-null    object
dtypes: object(7)
memory usage: 11.1+ KB
None

,ativo_id,sistema,criticidade,dominio,ambiente,localidade,status_ativo
0,A0001,Sistema_1,Crítica,Dominio_2,Homologação,São Paulo,Em desativação
1,A0002,Sistema_2,Média,Dominio_3,Produção,São Paulo,Em desativação
2,A0003,Sistema_3,Média,Dominio_4,Homologação,São Paulo,Ativo
3,A0004,Sistema_4,Alta,Dominio_5,Homologação,Campinas,Ativo
4,A0005,Sistema_5,Alta,Dominio_6,Produção,Recife,Ativo
5,A0006,Sistema_6,Baixa,Dominio_7,Produção,São Paulo,Ativo
6,A0007,Sistema_7,Baixa,Dominio_8,Produção,São Paulo,Ativo
7,A0008,Sistema_8,Alta,Dominio_9,Produção,São Paulo,Ativo
8,A0009,Sistema_9,Baixa,Dominio_10,Desenvolvimento,Recife,Ativo
9,A0010,Sistema_10,Baixa,Dominio_11,Produção,Campinas,Ativo
10,A0011,Sistema_11,Baixa,Dominio_12,Produção,Campinas,Ativo
11,A0012,Sistema_12,Baixa,Dominio_1,Desenvolvimento,Recife,Em desativação
12,A0013,Sistema_13,Baixa,Dominio_2,NaN,São Paulo,Ativo
13,A0014,Sistema_14,Crítica,Dominio_3,Homologação,Campinas,Ativo
14,A0015,Sistema_15,Média,Dominio_4,Homologação,Recife,Ativo
15,A0016,Sistema_16,Baixa,Dominio_5,Homologação,Campinas,Ativo
16,A0017,Sistema_17,,Dominio_6,Produção,Campinas,Ativo
17,A0018,Sistema_18,Média,Dominio_7,Produção,Recife,Ativo
18,A0019,Sistema_19,Média,Dominio_8,Homologação,Curitiba,Em desativação
19,A0020,Sistema_20,Alta,Dominio_9,Produção,Recife,Em desativação
20,A0021,Sistema_21,Baixa,Dominio_10,Produção,São Paulo,Ativo
21,A0022,Sistema_22,Baixa,Dominio_11,Produção,São Paulo,Ativo
22,A0023,Sistema_23,Média,Dominio_12,Desenvolvimento,Campinas,Em desativação
23,A0024,Sistema_24,Baixa,Dominio_1,Produção,São Paulo,Ativo
24,A0025,Sistema_25,Média,Dominio_2,Desenvolvimento,São Paulo,Ativo
25,A0026,Sistema_26,Baixa,Dominio_3,Produção,Recife,Ativo
26,A0027,Sistema_27,Baixa,Dominio_4,Produção,Campinas,Ativo
27,A0028,Sistema_28,Baixa,Dominio_5,Produção,Campinas,Em desativação
28,A0029,Sistema_29,Média,Dominio_6,Produção,Curitiba,Em desativação
29,A0030,Sistema_30,Crítica,Dominio_7,Desenvolvimento,Curitiba,Ativo
30,A0031,Sistema_31,Alta,Dominio_8,Desenvolvimento,São Paulo,Ativo
31,A0032,Sistema_32,Baixa,Dominio_9,Desenvolvimento,Campinas,Ativo
32,A0033,Sistema_33,Média,Dominio_10,Homologação,Campinas,Ativo
33,A0034,Sistema_34,,Dominio_11,Produção,Curitiba,Em desativação
34,A0035,Sistema_35,Baixa,Dominio_12,Produção,Curitiba,Em desativação
35,A0036,Sistema_36,Crítica,Dominio_1,Homologação,Recife,Em desativação
36,A0037,Sistema_37,Média,Dominio_2,Homologação,São Paulo,Ativo
37,A0038,Sistema_38,Média,Dominio_3,Desenvolvimento,Curitiba,Ativo
38,A0039,Sistema_39,Crítica,Dominio_4,Desenvolvimento,Campinas,Ativo
39,A0040,Sistema_40,Média,Dominio_5,Produção,Campinas,Ativo
40,A0041,Sistema_41,Alta,Dominio_6,Homologação,Campinas,Em desativação
41,A0042,Sistema_42,Crítica,Dominio_7,Desenvolvimento,São Paulo,Ativo
42,A0043,Sistema_43,Alta,Dominio_8,Produção,Curitiba,Ativo
43,A0044,Sistema_44,Alta,Dominio_9,Produção,Campinas,Ativo
44,A0045,Sistema_45,Média,Dominio_10,Desenvolvimento,Curitiba,Ativo
45,A0046,Sistema_46,Baixa,Dominio_11,Homologação,Recife,Ativo
46,A0047,Sistema_47,Média,Dominio_12,Desenvolvimento,Recife,Ativo
47,A0048,Sistema_48,Baixa,Dominio_1,Produção,Curitiba,Ativo
48,A0049,Sistema_49,Baixa,Dominio_2,Homologação,São Paulo,Ativo
49,A0050,Sistema_50,Média,Dominio_3,Homologação,Campinas,Em desativação

In [21]:
print(df_ativos['criticidade'].value_counts())
print('-' * 50)
print(df_ativos['ambiente'].value_counts())
print('-' * 50)
print(df_ativos['localidade'].value_counts())
print('-' * 50)
print(df_ativos['status_ativo'].value_counts())

criticidade
Baixa      58
Média      46
Crítica    45
Alta       42
Media       4
            3
Critica     1
Name: count, dtype: int64
--------------------------------------------------
ambiente
Produção           75
Homologação        65
Desenvolvimento    58
Name: count, dtype: int64
--------------------------------------------------
localidade
Recife       53
Campinas     50
São Paulo    49
Curitiba     48
Name: count, dtype: int64
--------------------------------------------------
status_ativo
Ativo             151
Em desativação     49
Name: count, dtype: int64

In [24]:
df_ativos

,ativo_id,sistema,criticidade,dominio,ambiente,localidade,status_ativo
0,A0001,Sistema_1,CRÍTICA,Dominio_2,Homologação,São Paulo,Em desativação
1,A0002,Sistema_2,MÉDIA,Dominio_3,Produção,São Paulo,Em desativação
2,A0003,Sistema_3,MÉDIA,Dominio_4,Homologação,São Paulo,Ativo
3,A0004,Sistema_4,ALTA,Dominio_5,Homologação,Campinas,Ativo
4,A0005,Sistema_5,ALTA,Dominio_6,Produção,Recife,Ativo
...,...,...,...,...,...,...,...
195,A0196,Sistema_196,BAIXA,Dominio_5,Desenvolvimento,Recife,Ativo
196,A0197,Sistema_197,ALTA,Dominio_6,Homologação,Curitiba,Ativo
197,A0198,Sistema_198,BAIXA,Dominio_7,Desenvolvimento,São Paulo,Em desativação
198,A0199,Sistema_199,CRÍTICA,Dominio_8,Homologação,Recife,Ativo
199,A0200,Sistema_200,ALTA,Dominio_9,Homologação,Curitiba,Ativo

In [19]:
print(df_vulnerabilidades.info())
df_vulnerabilidades.head(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   vuln_id        2000 non-null   object
 1   ativo_id       2000 non-null   object
 2   severidade     1974 non-null   object
 3   origem         2000 non-null   object
 4   data_abertura  2000 non-null   object
 5   data_correcao  469 non-null    object
 6   status         2000 non-null   object
 7   cvss_score     2000 non-null   float64
dtypes: float64(1), object(7)
memory usage: 125.1+ KB
None

,vuln_id,ativo_id,severidade,origem,data_abertura,data_correcao,status,cvss_score
0,V00001,A0078,Baixa,Cloud Security,21/03/2026,NaN,Em tratamento,2.8
1,V00002,A0060,Alta,Qualys,01/06/2026,NaN,Em tratamento,7.5
2,V00003,A0080,Alta,Veracode,18/08/2026,NaN,Aberta,1.7
3,V00004,A0086,Alta,Qualys,16/06/2026,NaN,Aberta,2.5
4,V00005,A0089,Alta,Cloud Security,12/02/2026,NaN,Em tratamento,4.4
5,V00006,A0025,Crítica,Cloud Security,02/05/2026,NaN,Aberta,8.9
6,V00007,A0061,Média,Veracode,29/03/2026,NaN,Aceita,5.9
7,V00008,A0189,Baixa,Pentest,12/01/2026,NaN,Aceita,4.4
8,V00009,A0186,Alta,Veracode,15/03/2026,NaN,Em tratamento,3.1
9,V00010,A0173,Baixa,Veracode,16/09/2026,NaN,Em tratamento,1.7
10,V00011,A0044,Alta,Qualys,13/09/2026,NaN,Aberta,3.1
11,V00012,A0046,Crítica,Veracode,13/09/2026,NaN,Aceita,5.6
12,V00013,A0060,Baixa,Pentest,09/02/2026,14/03/2026,Corrigida,2.7
13,V00014,A0039,Alta,Qualys,08/04/2026,NaN,Aberta,4.2
14,V00015,A0078,Baixa,Cloud Security,06/02/2026,NaN,Em tratamento,3.3
15,V00016,A0019,Baixa,Cloud Security,08/06/2026,NaN,Aberta,6.4
16,V00017,A0037,Média,Cloud Security,21/06/2026,NaN,Em tratamento,8.1
17,V00018,A0188,Baixa,Cloud Security,04/06/2026,NaN,Aberta,4.9
18,V00019,A0090,Média,Pentest,05/03/2026,NaN,Em tratamento,9.6
19,V00020,A0180,Média,Qualys,17/05/2026,NaN,Aberta,0.2
20,V00021,A0183,Média,Cloud Security,11/07/2026,NaN,Aceita,3.9
21,V00022,A0046,Alta,Cloud Security,02/04/2026,29/04/2026,Corrigida,7.6
22,V00023,A0200,NaN,Veracode,08/08/2026,26/09/2026,Corrigida,2.7
23,V00024,A0147,Média,Qualys,22/07/2026,NaN,Aceita,7.1
24,V00025,A0060,Baixa,Veracode,26/04/2026,NaN,Em tratamento,9.6
25,V00026,A0089,Baixa,Cloud Security,14/06/2026,NaN,Aberta,3.4
26,V00027,A0172,Crítica,Pentest,02/05/2026,NaN,Aberta,1.4
27,V00028,A0070,Alta,Veracode,09/09/2026,NaN,Em tratamento,2.5
28,V00029,A0033,Alta,Cloud Security,22/05/2026,NaN,Aceita,0.7
29,V00030,A0145,Baixa,Qualys,13/05/2026,31/05/2026,Corrigida,2.4
30,V00031,A0197,Baixa,Pentest,04/06/2026,NaN,Aberta,1.8
31,V00032,A0107,Média,Qualys,23/08/2026,NaN,Aceita,0.6
32,V00033,A0038,Baixa,Qualys,08/08/2026,NaN,Em tratamento,5.2
33,V00034,A0011,Média,Veracode,09/03/2026,NaN,Em tratamento,0.3
34,V00035,A0017,Crítica,Cloud Security,16/09/2026,NaN,Aceita,3.0
35,V00036,A0050,Média,Veracode,20/07/2026,NaN,Em tratamento,8.3
36,V00037,A0009,Alta,Pentest,03/06/2026,03/08/2026,Corrigida,1.5
37,V00038,A0101,Média,Veracode,06/03/2026,NaN,Em tratamento,0.9
38,V00039,A0096,Alta,Cloud Security,06/07/2026,NaN,Aberta,8.6
39,V00040,A0183,Crítica,Cloud Security,09/07/2026,NaN,Aberta,9.6
40,V00041,A0199,Média,Veracode,24/02/2026,NaN,Em tratamento,8.3
41,V00042,A0078,Baixa,Pentest,06/05/2026,NaN,Aceita,2.1
42,V00043,A0085,Média,Cloud Security,04/09/2026,24/11/2026,Corrigida,3.8
43,V00044,A0150,Média,Cloud Security,23/03/2026,NaN,Aceita,5.3
44,V00045,A0166,Alta,Qualys,15/03/2026,NaN,Aceita,6.7
45,V00046,A0101,NaN,Pentest,19/04/2026,NaN,Em tratamento,0.3
46,V00047,A0167,Alta,Pentest,03-29-2026,NaN,Em tratamento,2.6
47,V00048,A0036,Baixa,Qualys,13/07/2026,NaN,Em tratamento,0.7
48,V00049,A0163,Alta,Qualys,23/03/2026,NaN,Em tratamento,8.6
49,V00050,A0088,Média,Cloud Security,15/04/2026,NaN,Aceita,5.7